services:
  - type: web
    name: bot-tugas
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DEFAULT_NAMA
        value: Sahrul Mubarok
      - key: DEFAULT_NIM
        value: 202511420106
